import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
// import Header from "@/components/general/Header";
// import Sidebar from "@/components/general/Sidebar";
import { Toaster } from "react-hot-toast";
import ThemeProvider from "./Theme-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-9xl
          mx-auto
          px-4
          py-2
          sm:px-6
          lg:px-8`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {/* <Header /> */}
            {/* <div className="flex min-h-screen">
            <Sidebar />
            <div className=" border-2 flex-1 p-4 bg-gray-100 overflow-y-auto">
              {children}
            </div>
          </div> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
